---
title: 'Metabolic Model Application: Predicted Effects of Exogenous Metabolites on Mtb Growth at Varying Antibiotic Pressures'
author: 'Matthew Onorato'
version: '0.0.2'
date: '9/25/2020'
maintainer: 'Matthew Onorato'
email: 'monorato2@gmail.com' > 'monorato4398@sdsu.edu'
status: 'final'
output: html_document
---

DESCRIPTION: This script creates line plots of doubling times for each drug.

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(ggplotify)
library(patchwork)
library(ggtext)

rm(list = ls())

work_dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(work_dir)
getwd()

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dt_path <- '../../results/'

dt_file = list.files(dt_path, pattern='^iMtb.*supplements_lim.*gradient.xlsx')

`%!in%` = Negate(`%in%`)

media_nm <- colnames(read_excel(paste0(dt_path, dt_file)))[2]
```


First Line Drugs: Isoniazid + Ethambutol + Pyrazinamide
```{r}
fld_lim_e <- read_excel(paste0(dt_path, dt_file), sheet='first_line_drugs') %>%
    select(gradient, media_nm, ends_with('_e')) %>% 
    pivot_longer(cols=media_nm:length(.)) %>%
    mutate(gradient=if_else(gradient != 0, log10(gradient), -13),
           value=log10(value))

fld_lim_e[sapply(fld_lim_e, is.infinite)] <- 0

no_supp_gr_fld_e <- fld_lim_e %>% filter(gradient==-13) %>%
        filter(name==media_nm) %>% .$'value' %>% round(2)

to_col_fld_e <- fld_lim_e %>% filter(gradient==-13) %>%
        filter(value > no_supp_gr_fld_e) %>% pull(name)

df_col_fld_e <- fld_lim_e %>% filter(name %in% to_col_fld_e)

df_grey_fld_e <- fld_lim_e %>% filter(name %!in% to_col_fld_e) %>%
  filter(name!=media_nm)

df_black_fld_e <- fld_lim_e %>% filter(name==media_nm)

fel_s <- 'First Line Drugs: Isoniazid + Ethambutol + Pyrazinamide'

fel = ggplot() +
      geom_line(df_col_fld_e, mapping=aes(x=gradient, y=value, group=name),
                color='#00A5B5', size=0.3) +
      geom_line(df_grey_fld_e, mapping=aes(x=gradient, y=value, group=name),
                color=alpha('grey', 0.2), size=0.3) + 
      geom_line(df_black_fld_e, mapping=aes(x=gradient, y=value, group=name),
                color='black', size=0.6) + theme_classic(base_size=15) +
      labs(tag='A', title=fel_s, x='', y='Doubling Time (Log10) (hrs)') +
      scale_x_reverse(breaks=c(3, -1, -5, -9, -13),
                      labels=c('0%', '> 99%', '> 99.9%', '> 99.99%', '100%')) +
      theme(plot.title=element_text(face='bold'),
            axis.title=element_text(face='bold'),
            axis.text=element_text(size=14, face='bold'))
```


Isoniazid
```{r}
inh_lim_e <- read_excel(paste0(dt_path, dt_file), sheet='Rv1484_Rv2245') %>%
    select(gradient, media_nm, ends_with('_e')) %>% 
    pivot_longer(cols=media_nm:length(.)) %>%
    mutate(gradient=if_else(gradient != 0, log10(gradient), -13),
           value=log10(value))

inh_lim_e[sapply(inh_lim_e, is.infinite)] <- 0

no_supp_gr_inh_e <- inh_lim_e %>% filter(gradient==-13) %>%
        filter(name==media_nm) %>% .$'value' %>% round(2)

to_col_inh_e <- inh_lim_e %>% filter(gradient==-13) %>%
        filter(value > no_supp_gr_inh_e) %>% pull(name)

df_col_inh_e <- inh_lim_e %>% filter(name %in% to_col_inh_e)

df_grey_inh_e <- inh_lim_e %>% filter(name %!in% to_col_inh_e) %>%
  filter(name!=media_nm)

df_black_inh_e <- inh_lim_e %>% filter(name==media_nm)

iel = ggplot() +
      geom_line(df_col_inh_e, mapping=aes(x=gradient, y=value, group=name),
                color='#00A5B5', size=0.3) +
      geom_line(df_grey_inh_e, mapping=aes(x=gradient, y=value, group=name),
                color=alpha('grey', 0.2), size=0.3) +
      geom_line(df_black_inh_e, mapping=aes(x=gradient, y=value, group=name),
                color='black', size=0.6) + theme_classic(base_size=15) +
      labs(tag='B', title='Isoniazid', x='', y='Doubling Time (Log10) (hrs)') +
      scale_x_reverse(breaks=c(3, -1, -5, -9, -13),
                      labels=c('0%', '> 99%', '> 99.9%', '> 99.99%', '100%')) +
      theme(plot.title=element_text(face='bold'),
            axis.title=element_text(face='bold'),
            axis.text=element_text(size=14, face='bold'))
```


Ethambutol
```{r}
eth_lim_e <- read_excel(paste0(dt_path, dt_file), sheet='Rv3795_Rv3806c') %>%
    select(gradient, media_nm, ends_with('_e')) %>% 
    pivot_longer(cols=media_nm:length(.)) %>%
    mutate(gradient=if_else(gradient != 0, log10(gradient), -13),
           value=log10(value))

eth_lim_e[sapply(eth_lim_e, is.infinite)] <- 0

no_supp_gr_eth_e <- eth_lim_e %>% filter(gradient==-13) %>%
        filter(name==media_nm) %>% .$'value' %>% round(2)

to_col_eth_e <- eth_lim_e %>% filter(gradient==-13) %>%
        filter(value > no_supp_gr_eth_e) %>% pull(name)

df_col_eth_e <- eth_lim_e %>% filter(name %in% to_col_eth_e)

df_grey_eth_e <- eth_lim_e %>% filter(name %!in% to_col_eth_e) %>%
  filter(name!=media_nm)

df_black_eth_e <- eth_lim_e %>% filter(name==media_nm)

eel = ggplot() +
      geom_line(df_col_eth_e, mapping=aes(x=gradient, y=value, group=name),
                color='#00A5B5', size=0.3) +
      geom_line(df_grey_eth_e, mapping=aes(x=gradient, y=value, group=name),
                color=alpha('grey', 0.2), size=0.3) +
      geom_line(df_black_eth_e, mapping=aes(x=gradient, y=value, group=name),
                color='black', size=0.6) + theme_classic(base_size=15) +
      labs(tag='C', title='Ethambutol', x='', y='Doubling Time (Log10) (hrs)') +
      scale_x_reverse(breaks=c(3, -1, -5, -9, -13),
                      labels=c('0%', '> 99%', '> 99.9%', '> 99.99%', '100%')) +
      theme(plot.title=element_text(face='bold'),
            axis.title=element_text(face='bold'),
            axis.text=element_text(size=14, face='bold'))
```


Pyrazinamide
```{r}
pza_lim_e <- read_excel(paste0(dt_path, dt_file), sheet='Rv3601c') %>%
    select(gradient, media_nm, ends_with('_e')) %>% 
    pivot_longer(cols=media_nm:length(.)) %>%
    mutate(gradient=if_else(gradient != 0, log10(gradient), -13),
           value=log10(value))

pza_lim_e[sapply(pza_lim_e, is.infinite)] <- 0

no_supp_gr_pza_e <- pza_lim_e %>% filter(gradient==-13) %>%
        filter(name==media_nm) %>% .$'value' %>% round(2)

to_col_pza_e <- pza_lim_e %>% filter(gradient==-13) %>%
        filter(value > no_supp_gr_pza_e) %>% pull(name)

df_col_pza_e <- pza_lim_e %>% filter(name %in% to_col_pza_e)

df_grey_pza_e <- pza_lim_e %>% filter(name %!in% to_col_pza_e) %>%
  filter(name!=media_nm)

df_black_pza_e <- pza_lim_e %>% filter(name==media_nm)

pel = ggplot() +
      geom_line(df_col_pza_e, mapping=aes(x=gradient, y=value, group=name),
                color='#00A5B5', size=0.3) +
      geom_line(df_grey_pza_e, mapping=aes(x=gradient, y=value, group=name),
                color=alpha('grey', 0.2), size=0.3) +
      geom_line(df_black_pza_e, mapping=aes(x=gradient, y=value, group=name),
                color='black', size=0.6) + theme_classic(base_size=15) +
      labs(tag='D', title='Pyrazinamide', x='Drug Target Inhibition (Log10)',
           y='Doubling Time (Log10) (hrs)') +
      annotate('text', x=-12, y=2.4, size=6, fontface='bold', color='#00A5B5',
               label=paste0('+ ', length(to_col_pza_e), ' metabolites')) +
      annotate('text', x=-11.9, y=1.95, size=4, color='#00A5B5',
               label='(individually supplemented)') +
      scale_x_reverse(breaks=c(3, -1, -5, -9, -13),
                      labels=c('0%', '> 99%', '> 99.9%', '> 99.99%', '100%')) +
      theme(plot.title=element_text(face='bold'),
            axis.title=element_text(face='bold'),
            axis.text=element_text(size=14, face='bold'))
```


Combining all plots into one (patchwork)
```{r}
cap <- textbox_grob('**Figure 8. Predicted Effects of Exogenous Metabolites on
                    *Mtb* Growth at Varying Antibiotic Pressures.** Varying
                    antibiotic presssure is represented on the x-axis as
                    different degrees of enzymatic target inhibition ranging
                    from 0% to 100% and log-10 transformed. This was modeled by
                    setting reaction bounds for each antibitoic to a value of
                    1000, 10, 0.1, 1E-03, 1E-05, 1E-07, 1E-09, 1E-11, or 0.
                    Model growth is shown on the y-axis as doubling time in
                    hours and log-10 transformed. If the doubling time reaches 0
                    hours, then complete growth inhibition has been achieved.
                    For each plot, the black line represents *Mtb* growth in
                    unsupplemented *in vivo* media at different antibiotic
                    pressures. The colored and grey lines represent *Mtb* growth
                    in media supplemented with a single exogenous metabolite.
                    The colored lines are for metabolites able to overcome
                    antibiotic-induced growth inhibition at 100% enzymatic
                    inhibition (complete antibiotic pressure). The grey lines
                    are for metabolites unable to sustain growth at 100%
                    enzymatic inhibition.',
        gp=gpar(fontsize=14), x=unit(0.51, 'npc'), y=unit(0.55, 'npc'),
        width=unit(0.97, 'npc'))

dt_all <- grid.arrange(fel, iel, eel, pel, cap, heights=c(1, 1, 1, 1, 0.5))

ggsave('../../results/plots/1_supplement_effects_on_drug_targets_limited.png',
       plot=dt_all, width=12, height=20, unit ='in')
```