---
title: 'Metabolic Model Validation: Gene Essentiality Accuracy and Percentage of Unblocked Reactions by Subsystem'
author: 'Matthew Onorato'
version: '0.0.3'
date: '9/17/2020'
maintainer: 'Matthew Onorato'
email: 'monorato2@gmail.com' > 'monorato4398@sdsu.edu'
status: 'final'
output: html_document
---

DESCRIPTION: This script hierarchically clusters subsystems by gene essentiality
             accuracy (via Euclidean distance) and then creates a heatmap to
             visualize the results.

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(RColorBrewer)
library(pheatmap)
library(dendsort)
library(gridExtra)
library(grid)
library(gridtext)
library(ggplotify)
library(patchwork)
library(ggtext)

rm(list = ls())

work_dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(work_dir)
getwd()

knitr::opts_chunk$set(echo = TRUE)
```


Subsystem accuracies and percent of unblocked reactions for iMtb_H37Rv_1132
```{r}
path_subs_iMtb = '../data/iMtb_H37Rv_1132_subsystem_accuracy.xlsx'

ss_ess_acc_iMtb <- read_excel(path_subs_iMtb, sheet='gene_essentiality')

ss_unblk_acc_iMtb <- read_excel(path_subs_iMtb, sheet='unblocked_reactions')

ss_acc_iMtb <- merge(ss_ess_acc_iMtb, ss_unblk_acc_iMtb, by='Subsystem') %>%
    dplyr::filter(Subsystem != 'Biomass Production' &
                  Subsystem != 'Non-Growth Associated Maintenance' &  
                  Subsystem != 'Extracellular Exchange' &
                  Subsystem != 'Intracellular Demand') %>%
    column_to_rownames(var='Subsystem')

# sorts strains by gene essentiality accuracy only (not blocked reactions)
cluster_rows <- hclust(dist(ss_acc_iMtb, method='euclidean'))
sort_hclust <- function(...) as.hclust(dendsort(as.dendrogram(...)))
cluster_rows <- sort_hclust(cluster_rows)

ss_acc_iMtb[ss_acc_iMtb == 0] <- NA

colors_iMtb <- colorRampPalette(brewer.pal(n=8, name='YlGn'))(10)

# creates heatmap of strains, sorting included
sub <- pheatmap(ss_acc_iMtb, cellwidth=12, cellheight=12, fontsize_col=10,
                cluster_cols=FALSE, color=colors_iMtb, na_col='white',
                border_color='black', cutree_rows=6, gaps_col=c(6, 12),
                legend_breaks=c(20,40,60,80,100),
                legend_labels=c('20%', '40%', '60%', '80%', '100%'),
                cluster_rows=cluster_rows, clustering_distance_rows='euclidean',
                filename=NA, width=7.2, height=8)

cap <- expression(bold('Figure 4. Gene Essentiality Accuracy and Percentage of Unblocked Reactions by Subsystem'))

sub_cap <- as.ggplot(sub) + labs(caption=cap) +
    theme(plot.caption=element_text(hjust=0.1, size=12))

ggsave('4_essentiality_susbystem_accuracy.png',
       plot=sub_cap, height=8.9, width=7.4, unit ='in')
```
